# ci pipeline
sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ayubtalha/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ayubtalha/docker-react npm run test
