sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ayubtalha/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ayubtalha/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'frontend'
  env: 'Frontend-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-558025156334'
  bucket_path: 'frontend'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: '$AWS_SECRET_KEY'
